name: Update README

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  reorganize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate table with `ppm`
        run: |
          wget https://github.com/pragtical/plugin-manager/releases/download/v1.0.10/ppm.x86_64-linux -O ppm
          chmod +x ppm
          ./ppm table manifest.json README.md
          if ! git diff --exit-code -s README.md; then
            git config --global user.name "Github Actions" && git config --global user.email "<>"
            git add README.md
            git commit -m '[CI] Updated README.md.'
            git push
          fi
